# Generated by Django 3.2 on 2022-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20220731_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='people',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='B+', max_length=3),
        ),
        migrations.AddField(
            model_name='people',
            name='martial_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=10),
        ),
    ]
