# Generated by Django 3.2 on 2022-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20220915_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='mobile_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
