# Generated by Django 3.2 on 2022-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20221003_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='landline',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
